# Generated by Django 3.0.5 on 2020-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosworkinout', '0003_auto_20200425_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='reps',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
