# Generated by Django 3.0.5 on 2020-04-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosworkinout', '0004_auto_20200425_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reps',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
