# Generated by Django 3.0.5 on 2020-04-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoosworkinout', '0005_auto_20200425_1944'),
    ]

