# Generated by Django 3.0.5 on 2020-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosworkinout', '0006_remove_reps_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workedoutat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
